
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mohsi
 */
public class Student_Dashboard extends javax.swing.JFrame {
     Scanner scan = new Scanner(System.in);
    /**
     * Creates new form New_profile
     */
    public Student_Dashboard() {
        initComponents();
    }
    String userID="";
    public Student_Dashboard(String userid) {
        initComponents();
        this.userID = userid;
        System.out.println("Found userid " + userid);
//          RUN SELECT QUERY HERE GET ALL THE INPUT try{

        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/empdb", "root", "root");
            Statement stmt = con.createStatement();
            
            String qry = "select * from std_Registration where studentID = '" + userid + "'";
            
            ResultSet rs = stmt.executeQuery(qry);
            while (rs.next()) {
                txtname.setText(rs.getString(1));
                txtmobile.setText(rs.getString(2));
                txtemail.setText(rs.getString(3));                
                txtid.setText(rs.getString(4));
                txtpassword.setText(rs.getString(5));
                txtstate.setText(rs.getString(6));
                txtcity.setText(rs.getString(7));
                txtcourse.setText(rs.getString(8));
                txtfees.setText(rs.getString(9));
                txtpaid.setText(rs.getString(10));                
                txtremaining.setText(rs.getString(11));
                
            }
        } catch (Exception ex) {
            System.out.println("Exception occured " + ex.getMessage());
        }
    }
    /**
     * Creates new form Student_Dashboard
     */
//    public Student_Dashboard() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        btncoursedetails = new javax.swing.JButton();
        btnmyprofile = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcourse = new javax.swing.JTextField();
        txtpaid = new javax.swing.JTextField();
        txtfees = new javax.swing.JTextField();
        txtremaining = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(112, 125, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setBackground(new java.awt.Color(255, 0, 0));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogout.setText("LogOut");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 471, -1, -1));

        btncoursedetails.setBackground(new java.awt.Color(0, 255, 0));
        btncoursedetails.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btncoursedetails.setText("Course Details");
        btncoursedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoursedetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btncoursedetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 194, -1, 30));

        btnmyprofile.setBackground(new java.awt.Color(0, 238, 5));
        btnmyprofile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnmyprofile.setText("My Profile");
        btnmyprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmyprofileActionPerformed(evt);
            }
        });
        jPanel1.add(btnmyprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 78, 133, 30));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 580));

        jLabel16.setIcon(new javax.swing.ImageIcon("E:\\a-small-green-bird-sits-on-thin-branch-in-a-green-tree.jpg")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 580));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel2.setText("My Profile");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 25, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 86, 54, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("City");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 421, 54, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mobile");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 146, 54, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("State");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 368, 54, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 315, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 205, 54, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("StudentID");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 259, -1, -1));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 87, 208, -1));
        jPanel2.add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 147, 208, -1));
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 206, 208, -1));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 260, 208, -1));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 316, 208, -1));
        jPanel2.add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 369, 208, -1));
        jPanel2.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 422, 208, -1));

        btnupdate.setBackground(new java.awt.Color(0, 204, 0));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 534, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("E:\\a-small-green-bird-sits-on-thin-branch-in-a-green-tree.jpg")); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 590));

        jTabbedPane1.addTab("My Profile", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setText("Course Details");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 40, 123, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Course");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 136, 63, 22));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Paid");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 253, 63, 22));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Fees");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 199, 63, 22));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Remaining");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 304, -1, 22));
        jPanel3.add(txtcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 136, 171, 28));
        jPanel3.add(txtpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 247, 171, 28));
        jPanel3.add(txtfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 193, 171, 28));
        jPanel3.add(txtremaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 298, 171, 28));

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\a-small-green-bird-sits-on-thin-branch-in-a-green-tree.jpg")); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 590));

        jTabbedPane1.addTab("Course Details", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -30, 460, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
//        this.setVisible(false);
//        Admin_Dash ad = new Admin_Dash();
//        ad.setVisible(true);
        
        
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginFrame lg = new LoginFrame();
        lg.setVisible(true);

    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnmyprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmyprofileActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
//        
//        System.out.println(txtname.getText());
//        String Name = (String) txtname.getText();
//        System.out.println(txtmobile.getText());
//        String Mobile = (String) txtmobile.getText();
//        System.out.println(txtemail.getText());
//        String Email = (String) txtemail.getText();
//        System.out.println(txtid.getText());
//        String StudentID = (String) txtid.getText();
//        System.out.println(txtpassword.getText());
//        String Password = (String) txtpassword.getText();
//        System.out.println(txtstate.getText());
//        String State = (String) txtstate.getText();
//        System.out.println(txtcity.getText());
//        String City = (String) txtcity.getText();
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/empdb", "root", "root");
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery("select * from std_Registration where StudentID = '" + Name + "'");
//            while (rs.next()) {
//                String std_Registration = rs.getString("StudentID");
//                txtid.setText(std_Registration);
//            }
//        } catch (ClassNotFoundException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        
//        
    }//GEN-LAST:event_btnmyprofileActionPerformed

    private void btncoursedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoursedetailsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        
//        System.out.println(txtcourse.getText());
//        String Course = (String) txtcourse.getText();
//        System.out.println(txtfees.getText());
//        String Fees = (String) txtfees.getText();
//        System.out.println(txtpaid.getText());
//        String Paid = (String) txtpaid.getText();
//        System.out.println(txtremaining.getText());
//        String Remaining = (String) txtremaining.getText();
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/empdb", "root", "root");
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery("select * from std_Registration where Course = '" + Course + "','" + Fees + "','" + Paid + "','" + Remaining + "'");
//            while (rs.next()) {
//                String coursefee = rs.getString("java");
//                txtfees.setText(coursefee);
//            }
//        } catch (ClassNotFoundException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_btncoursedetailsActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
    String name = txtname.getText();
    String mobile = txtmobile.getText();
        String email = txtemail.getText();
        String studentid = txtid.getText();
        String password = txtpassword.getText();
        String state = txtstate.getText();
        String city = txtcity.getText();
         
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/empdb", "root", "root");
            Statement stmt = con.createStatement();
            
            String str = "UPDATE std_registration set Name ='"+name+"',Email='"+ email + "',Mobile='" + mobile +"',StudentID='"+studentid+"',Password='"+password+"',State='" + state +"',City='" + city + "'WHERE StudentID='"+studentid + "'";
           stmt.executeUpdate(str);
           JOptionPane.showMessageDialog(null, "Update successfull"); 
      
          } catch(Exception e){
           System.out.println("Exception occured " + e.getMessage());
          }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Student_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncoursedetails;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmyprofile;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfees;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpaid;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtremaining;
    private javax.swing.JTextField txtstate;
    // End of variables declaration//GEN-END:variables
}
